version: '3.8'

services:
  sentinel1:
    image: redis
    container_name: redis_sentinel1
    ports:
      - 26379:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      redis-source_redis_network:
        ipv4_address: 172.20.0.5
  sentinel2:
    image: redis
    container_name: redis_sentinel2
    ports:
      - 26380:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      redis-source_redis_network:
        ipv4_address: 172.20.0.6
  sentinel3:
    image: redis
    container_name: redis_sentinel3
    ports:
      - 26381:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel3.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      redis-source_redis_network:
        ipv4_address: 172.20.0.7
networks:
  redis-source_redis_network:
    external:
      name: redis-source_redis_network